<a href="https://colab.research.google.com/github/kushagarwal2910-lang/CAcalc/blob/main/pytorch%2B%2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch #gives the core functionalities of pytorch
import torch.nn as nn #components for building neural networks
import torch.optim as optim #tools for training those networks

tensors

In [ ]:
distances = torch.tensor([[1.0],[2.0],[3.0],[4.0]], dtype=torch.float32)
times = torch.tensor([[6.96],[12.11],[16.77],[22.21]], dtype=torch.float32)
#here in tensor we created a nested square bracket
#outer square bracket called batch
#inner square brackets called sample

~~~~~~~~~~~~~~~~~~~~~~~~~
Use float32 when:

  .)Debugging

  .)Small models

  .)Scientific precision matters

  .)Loss suddenly becomes NaN

Use bfloat16 when:

  .)Training large models

  .)Memory is tight

  .)Speed matters

  .)Using TPUs or modern GPUs


In [ ]:
x = torch.arange(6).reshape(2,3)
#creating its transpose
y = x.t()

In [ ]:
#Contiguous = stored continuously in memory in the expected order.
e = y.is_contiguous()
e

False

In [ ]:
#to make the matrice contiguous
y = y.contiguous()
y.is_contiguous()
#always check .is_contiguous() before low level memeory operation like view()

True

In [ ]:
#generating a random tensor
torch.randn(2,12)#generates a 2d tensor(matrice) of size 2x12 with filling random elements
#if we wnt we can write torch.randn(x,y,z,w) then it gives a 4d vector

tensor([[ 0.0180,  0.5418, -0.3213,  0.0197,  0.4218,  1.5255,  1.5247,  0.5550,
          0.4713,  0.1555,  1.1078,  0.9898],
        [ 0.8861, -0.5836, -0.9392,  1.6625, -0.0998,  0.7089, -0.1322,  0.6406,
          0.4187, -0.6999, -1.0402, -0.2785]])

In [ ]:
#broadcasting-it allows you to perform math b/w tensors of difft shapes without copying data
#broadcasting virtually expands smaller tensor

#batch of 32 images, 3 rgb channels, 64x64 pixels
images = torch.randn(32,3,64,64)

#if we want to normalize each channel (r,g,b) with a specific mean
mean = torch.tensor([0.5,0.4, 0.3]) #shape: 3

#View mean as (1,3,1,1) so it broadcasts over batch, H and W
mean = mean.view(1,3,1,1)
#this changes the dimension of mean tensor from 1d to 4d as of images named tensor
#dimensionized so that it can perform operations with images named tensor

#pytorch virtually expands 'mean' to (32,3,64,64) instantly
normalized = images-mean

In [ ]:
#engiene matrix operation
# matmul is the standard dot product
# torch.bmm is batch matrix multiply, it ignores broadcasting rules for safety

# Batch of 10 users, 5 items per user, embedding size 64
User_Embeddings = torch.randn(10, 5, 64)

# Transposed Item Embeddings: Batch 10, 64 embedding size, 5 items
Item_Embeddings_T = torch.randn(10, 64, 5)

# Calculate scores for every user-item pair in the batch
# (10, 5, 64) @ (10, 64, 5) -> (10, 5, 5)
scores = torch.bmm(User_Embeddings, Item_Embeddings_T)

In [ ]:
#squeeze and unsqueeze
x = torch.tensor([2,0,3])
x.shape

#unsqeze adds a axis with element 1 into the place where the dimension is assigned in brackets
#x.unsqueeze(dimension where the axis with element 1 to be added in x)
x = x.unsqueeze(0)#becomes row vector(1,3) this one in (1,3) is the axis added by unsqueeze
x = x.unsqueeze(1)#becomes column vector(3,1) this one in (3,1) is the axis added by unsqueeze
x = x.unsqueeze(2)#becomes 3d (3,1,1) this one in (3,1,1) is the axis added by unsqueeze
#note you cant directly jump from initial x to the 3d tensor of x
#you need to go through 1d then 2d then come to 3d

y = torch.tensor([2,3,4,1,3])

#squeeze removes the axis with dimension 1 if size > 1 then cant remove
y = y.squeeze(0) #dosent work as the dimension 0 have 3 as size

z = torch.tensor([[1],[2]])

z = z.squeeze(1)#as now the sizeof z is (2,1)
z

tensor([1, 2])

In [ ]:
#Advanced Indexing

#gather
'''
torch.gather(input, dim, index, *, sparse_grad=False, out=None)

.)input: The tensor from which you'll be extracting elements. Think of this as your source of data.

.)dim: The dimension along which you'll be gathering elements. If your tensor is a matrix (2D), this could be either the rows
  (dimension 0) or the columns (dimension 1). For higher-dimensional tensors, you have more choices.

.)index: This tensor holds the indices of the elements you want. Its shape should be compatible with the input tensor and the
 chosen dimension.

.)sparse_grad: (Optional) If True, the gradient with respect to the input will be a sparse tensor.

.)out: (Optional) The destination tensor.
'''
probs = torch.tensor([[0.1, 0.2, 0.7, 0.0],  # Model guessed class 2
                      [0.8, 0.1, 0.1, 0.0],  # Model guessed class 0
                      [0.0, 0.0, 0.1, 0.9]]) # Model guessed class 3

targets = torch.tensor([2, 0, 3]).unsqueeze(1) # Shape (3, 1)

selected_probs = torch.gather(input=probs, dim=1, index=targets)








#scatter

'''
torch.scatter writes values into a tensor at specific coordinates
defined by an index tensor (commonly used to create One-Hot vectors).

torch.scatter(input, dim, index, src, *, reduce='add', sparse_grad=False)

.)src: This is the source tensor containing the values that you want to scatter into the input
 tensor. Its shape must be compatible with the index tensor and the input tensor's dimensions.
'''
input_tensor = torch.zeros(3, 4)
index_tensor = torch.tensor([[0, 2],    # In row 0, scatter to column 0 and 2
                             [1, 3],    # In row 1, scatter to column 1 and 3
                             [0, 1]])   # In row 2, scatter to column 0 and 1
src_tensor = torch.tensor([[10., 20.],  # Values to scatter for row 0
                           [30., 40.],  # Values to scatter for row 1
                           [50., 60.]]) # Values to scatter for row 2

output_tensor = torch.scatter(input=input_tensor, dim=1, index=index_tensor, src=src_tensor)



In [ ]:
#einstein summation
'''
logic of syntax:#
1.)Indices (i, j, k, ...): Each letter represents a dimension (axis) of your tensor.
2.)Comma (, ): Separates different input tensors.
3.)Arrow (->): Separates the input structure from the desired output structure.
4.)Summation Rule: Any index found on the left side (input) but missing on the right side (output) is summed over (reduced).
'''

#element wise operation
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

out = torch.einsum("i,i->i", a, b)#element wise multiplication happens output is [4,10,18]

#dot product(vetor->scalar)
out = torch.einsum("i,i->", a, b) #value wil be (1.4 + 2.5 + 3.6 = 32) therefore the scalar result after dot product is 32

#outer product(vector -> matrix)
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5.])

out = torch.einsum("i,j->ij", a, b)#output is of size (3,2) i.e [[4,5],[8,10],[12,15]]

#vector matrix multiplication
A = torch.randn(3,4) #matrice
x = torch.randn(4)#treated as column matrix i.e (4,1) its called as a vector

out = torch.einsum("ij,j->i", A, x)#now (3,4).(4,1)-> 3 or (3,1) dimension

#matrix vector multiplication
A = torch.randn(4,3) #matrice
x = torch.randn(4)#treated as row matrix i.e (1,4) its called as a vector

out = torch.einsum("i,ij->j", x,A)#now (1,4).(4,3)-> 3 or (1,3) dimension

#transpose of matrix
A = torch.randn(2, 3)

out = torch.einsum("ij->ji", A)

#matrix multiply
A = torch.randn(2, 3)
B = torch.randn(3, 4)

out = torch.einsum("ik,kj->ij", A, B)

#batch matrix multiply
A = torch.randn(10, 2, 3)
B = torch.randn(10, 3, 4)

out = torch.einsum("bik,bkj->bij", A, B)#equivalent to torch.bmm(A, B)

#tensor contraction
A = torch.randn(3, 4, 5)
B = torch.randn(5, 4, 6)

out = torch.einsum("ijk,kjl->il", A, B) #dimension become (3,6)

#broadcasting multiplication
X = torch.randn(5, 3)
w = torch.randn(3)

out = torch.einsum("ij,j->ij", X, w)#dimension is (5,3)

#weighted sum over dimension
out = torch.einsum("ij,j->i", X, w)

#summation over one axis
X = torch.arange(4).resize(1,4)
out = torch.einsum("ij->j", X)#equivalent to X.sum(dim=0), output dimension matrice is of 4
#output is tensor([0, 1, 2, 3])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
out = torch.einsum("ij->i", X)#equivalent to X.sum(dim=1), output dimension matrice is of 1
#output is tensor([6])

#permuting high dimensional tensors
X = torch.randn(2, 3, 4)
out = torch.einsum("abc->bca", X)#out dimension is (3,4,2)

/usr/local/lib/python3.12/dist-packages/torch/_tensor.py:1002: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [ ]:
#stride
'''
Stride tells PyTorch how to read data from memory without copying it.

Why copying is a BIG problem in LLMs:
  Imagine training an LLM:
  Billions of parameters
  Huge tensors: (batch, sequence, heads, dim)
  Every layer does:
  reshape
  transpose
  split into heads
  merge heads back
If every reshape copied data:
  GPU memory would explode
  Training would be 10–50× slower
  LLM training would be impossible
Stride exists to avoid copying.

torch.stride() is never directly used in deeplearning but we use it's outcoe cases like
  view()
  reshape()
  permute()
  transpose()
  einsum()
  All of these depend on stride internally.
'''

#view- used to resize a tensor or flatten a tensor most commonly
# Example: Output from a Convolution layer
# Shape: (Batch_Size=64, Channels=32, Height=10, Width=10)
conv_output = torch.rand(64, 32, 10, 10)

# We want to flatten this to (Batch_Size, Everything_Else)
# -1 tells PyTorch to calculate that dimension automatically
flattened = conv_output.view(64, -1)

print(flattened.shape)
# Output: torch.Size([64, 3200]) -> Ready for Linear Layer



#reshape()
'''does almost the same thing as view(), but it is robust. If the data is contiguous, it returns a view (fast).
If the data is not contiguous, it automatically copies the data into a new chunk of memory (safe but slightly slower).

Use reshape() when you just want the code to work and don't want to worry about memory contiguity errors.
'''
# Create a tensor and transpose it (breaks memory contiguity)
x = torch.rand(2, 3).transpose(0, 1)
# x.view(6) -> This would RAISE AN ERROR because x is not contiguous
y = x.reshape(6) # This WORKS (it copies data if needed)
print(y)

#permute
# Image loaded from disk: (Batch=10, Height=256, Width=256, RGB_Channels=3)
raw_image_batch = torch.rand(10, 256, 256, 3)
# We need to move the Channels (index 3) to index 1.
# New order indices: 0 (Batch), 3 (Channels), 1 (Height), 2 (Width)
pytorch_ready = raw_image_batch.permute(0, 3, 1, 2)
print(pytorch_ready.shape)
# Output: torch.Size([10, 3, 256, 256]) -> Ready for Conv2d

#transpose
#Syntax: tensor.transpose(dim0, dim1)
# Data format: (Batch_Size=32, Sequence_Length=100, Embedding_Dim=512)
nlp_data = torch.rand(32, 100, 512)
# Swap Batch (0) and Sequence (1) for a specific LSTM implementation
lstm_input = nlp_data.transpose(0, 1)
print(lstm_input.shape)
# Output: torch.Size([100, 32, 512])

torch.Size([64, 3200])
tensor([0.8147, 0.3270, 0.1894, 0.2650, 0.3533, 0.3404])
torch.Size([10, 3, 256, 256])
torch.Size([100, 32, 512])


Autograd and data

In [ ]:
'''
Ground rule (mental model):
  .Every Tensor with requires_grad=True is a node
  .Every operation creates an edge
  .Backward = graph traversal (reverse topological order)
  .Graph is dynamic (rebuilt every forward pass)

'''

'''
What is the Computation Graph really?

A computation graph is just:
A record of “who produced whom” during computation.
example:
y = x * 2
z = y + 3
pytorch internally records [x → (multiply) → y → (add) → z]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

What is a node?

A node is:
A tensor or an operation result that exists in the graph
Examples of nodes: x,y,z
Each node:
  Knows how it was created
  Knows what came before it
In PyTorch:
  Every tensor created via an operation becomes a node.
  Leaf tensors are special.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

What is an edge?

An edge means:
“This tensor depends on that tensor”
Example:
y = x * 2
graphically: x ──edge──> y
That edge means:
  If y changes
  x influenced it
So when gradients flow:
  They travel backward along edges

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

what is DAG?

directed(D): have direction
acyclic(A): No loops
Graph(G)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Why do gradients “flow”?

Because each operation knows:
“If output gradient is g, how does input gradient look?”
example: y = x * 2 --------------> ∂y/∂x = 2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

leaf tenor?

it is a tensor created directly by you, not by an operation.
example:
  x = torch.tensor(3.0, requires_grad=True)
  here x is a leaf tensor.

  y = x * 2
  here y is not a leaf tensor.
Why does this matter?
  Only leaf tensors:
  Store gradients in .grad
  Are considered parameters (weights)
  hence according to example x.grad exists but y.grad doesnt exist.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''
#smallest possible graph
x = torch.tensor(2.0, requires_grad=True)
y = x * 3
y.backward()
print(x.grad)  # 3

#check graph connection
print(y.grad_fn)

#linear chain graph
x = torch.tensor(2.0, requires_grad=True)
y = x * 2
z = y + 3
loss = z ** 2
loss.backward()
print(x.grad)
'''on doing a loss.backward the gradients are calculated of loss then it flows to the Z then it flows to Y
then it flows to X and it is then the gradient is then stored into X.grad and it is stored in such a way as displayed below

∂loss/∂z = 14
∂z/∂y = 1
∂y/∂x = 2

x.grad = 14 * 1 * 2 = 28

'''

#inspect backward graph structure
print(y.grad_fn)# it tells you which operation produced the tensor

#leaf vs non-leaf
x = torch.randn(3, requires_grad=True)
y = x * 2
print(x.is_leaf)  # True
print(y.is_leaf)  # False

#intermedite gradients
x = torch.randn(3, requires_grad=True)
y = x * 2
y.retain_grad()#it is like .grad() which was for leaf tensors similarly .retain_grad() is for non-leaf tensors
z = y.sum()
z.backward()
print(y.grad)

#explicit
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = x * 2
y.backward(torch.tensor([1., 1., 1.]))
print(x.grad)

#dynamic graph (runtime decision)
x = torch.tensor(3.0, requires_grad=True)
if x > 0:
    y = x * 5
else:
    y = x / 5
y.backward()
print(x.grad)

#graph destroyed after backward
x = torch.tensor(2.0, requires_grad=True)
y = x * x
y.backward()
# y.backward()  # RuntimeError

#cut edge
x = torch.tensor(3.0, requires_grad=True)
y = x * 2
z = y.detach() * 3
z.requires_grad = True
z.backward()
print(x.grad)  # None
'''
x ──X──▶ y    y_detached ──▶ z

y.detach() is used when you want to use the value of y but completely stop gradients from flowing back through it.

or

y.detach() keeps the number the same, but tells PyTorch: “do not learn from this.”
'''

#no grad
x = torch.tensor(3.0, requires_grad=True)
with torch.no_grad():
    y = x * 4
print(y.requires_grad)#it is lik a flag telling autograd telling Do I care about gradients flowing through this tensor?
#we can turn it of manually as y.requires_grad_(False)

#matrix dag
X = torch.randn(4, 3, requires_grad=True)
W = torch.randn(2, 3, requires_grad=True)
Y = X @ W.T
loss = Y.sum()
loss.backward()
print(X.grad.shape)
print(W.grad.shape)

#autograd.grad
x = torch.tensor(4.0, requires_grad=True)
y = x ** 3
grad = torch.autograd.grad(y, x)
print(grad)

#higher order gradient
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
grad1 = torch.autograd.grad(y, x, create_graph=True)[0]
grad2 = torch.autograd.grad(grad1, x)[0]
print(grad1)  # first derivative
print(grad2)  # second derivative

#freeze part of graph
W = torch.randn(3, requires_grad=True)
b = torch.randn(3)
x = torch.randn(3)
y = W * x + b
loss = y.sum()
loss.backward()
print(W.grad)
print(b.grad)  # None


tensor(3.)
tensor(28.)
True
False
tensor([1., 1., 1.])
tensor([2., 2., 2.])
tensor(5.)
None
False
torch.Size([4, 3])
torch.Size([2, 3])
(tensor(48.),)
tensor(6., grad_fn=<MulBackward0>)
tensor(2.)
tensor([-0.4941,  0.6833,  0.7716])
None


In [ ]:
#retain graph

# Standard Usage syntax: loss.backward(retain_graph=True)
'''its use is: retain_graph=True tells PyTorch: "Calculate the gradients,
 but keep the graph structure in memory because I need to traverse it again."'''

x = torch.tensor([1.0], requires_grad=True)
w = torch.tensor([2.0], requires_grad=True)

y = x * w

loss1 = y * 2
loss2 = y ** 2

# We need to keep the graph of 'y = x * w' alive for loss2!
loss1.backward(retain_graph=True)

# Now we can destroy the graph, so retain_graph=False (default)
loss2.backward()

print(f"Gradient of x: {x.grad}")
# Result: loss1 grad (2*w=4) + loss2 grad (2*y*w = 2*2*2 = 8) = 12

Gradient of x: tensor([12.])


DataLoader's

In [ ]:
from torch.utils.data import Dataset

'''
Dataset is of 2 types

A) Map-style Datasets:
  This is what you will use 95% of the time. It maps an index (like 0, 1, 2) to a specific data sample.
  Syntax Requirement: You must implement two methods:

    .)__len__(self): Tells PyTorch "how many items do we have?"

    .)__getitem__(self, idx): Tells PyTorch "give me the item at index idx."

B)Iterable-style Datasets:
  Used for streaming data where you can't just say "give me item #500" because the data is coming in a stream (like reading a huge file line-by-line or a video stream).

  Syntax Requirement: You implement __iter__(self).
'''

#Map-style Datasets
class MyCustomDataset(Dataset):
  def __init__(self, data_list):
    # We store the data in the class
    self.data = data_list

  def __len__(self):
    #Required: Return total size
    return len(self.data)

  def __getitem__(self, idx):
    #Required: Return item at index idx
    return self.data[idx]
my_data = [10, 20, 30, 40, 50]
dataset = MyCustomDataset(my_data)
print(dataset[0])


#iterable style datasets
from torch.utils.data import IterableDataset
class MyStreamDataset(IterableDataset):
    def __iter__(self):
        # Yields data one by one (like a generator)
        for i in range(10):
            yield i


'''
DataLoader engiene
'''

loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=1,
    shuffle=False,
    sampler=None,
    batch_sampler=None,
    num_workers=1,
    collate_fn=None,
    pin_memory=False,
    drop_last=False,
    prefetch_factor=2,
    # ... there are more, but these are the critical ones
)
'''
batch_size: it controls how many samples are loaded per iteration

shuffle: if True, it reshuffles the data at every epoch

num_workers: it sets how many subprocesses to use for data loading
              .)(0): (default). It loads a batch, then trains, then loads the next.
              .)(>0): worker processes load data in background while the main processis training

              Note: On Windows, setting num_workers > 0 can sometimes cause errors
               if your code isn't inside if __name__ == '__main__': block.

collate_fn is not clearly described here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
collate_fn: crucial for NLP
            .)it's used to merge a list of samples into a batch.
            .)Default behavior: It simply stacks tensors (torch.stack).

pin_memory: if True, data loader copies tensors into CUDA-pinned memory

drop_last: if your dataset size is not divisible by the batch size, the last batch
           will be smaller. drop_last=True discards that incomplete last batch.

prefetch_factor: its related with num_workers
                 .)works only when num_workrs>0
                 .)When you set num_workers > 0, PyTorch creates a Queue
                 .)It is a buffer size. Increase it if your GPU is waiting for data. Decrease it if your computer runs out of RAM.

            Total batches in RAM = num_workers * prefetch_factor + 1
'''

#tensor dataset - Wraps tensors into a dataset immediately.
from torch.utils.data import TensorDataset, DataLoader

x = torch.randn(100,3)
y = torch.randint(0,2,(100,))
dataset = TensorDataset(x,y)
loader = DataLoader(dataset, batch_size=16)

#concatDataset - combines two datasets
from torch.utils.data import ConcatDataset

ds1 = TensorDataset(x[:50], y[:50])
ds2 = TensorDataset(x[50:], y[50:])
combined = ConcatDataset([ds1, ds2]) # Now has 100 samples again

#subset and random_split
from torch.utils.data import random_split
# Split dataset into 80% train, 20% val
train_ds, val_ds = random_split(dataset, [80, 20])

10


optimizer

In [ ]:
'''
What does torch.optim even do?

When you train a neural network (or any model), the goal is to reduce loss.
Optimizers in PyTorch are tools that help adjust the model’s parameters so that loss goes down over time.
They do this by using calculated gradients (from backprop) to update weights in a smarter way.

# 1. Zero out old gradients
optimizer.zero_grad()

# 2. Forward pass: compute predictions
predictions = model(inputs)

# 3. Compute loss
loss = loss_fn(predictions, targets)

# 4. Backward pass: compute gradients
loss.backward()

# 5. Update weights using optimizer
optimizer.step()
'''

#to create an optimizer
'''
every optimizer needs
.)parameters
.)learning rate(lr) - how big step to take toward reducing loss
'''
import torch.nn as nn

model = nn.Linear(10, 1)   # a simple linear model
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

#common optimizers to use are SGD, SGD with mommentum, ADAM, RMSprop


#SGD momentum:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

#ADAM
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

#learning rate and adjustment
'''
The learning rate (lr) is a crucial hyperparameter.
 Too high → training unstable; too low → training slow.

PyTorch also lets you use learning-rate schedulers that change the lr over
time during training, which often improves final results.
'''
from torch.optim.lr_scheduler import StepLR

scheduler = StepLR(optimizer, step_size=30, gamma=0.1)#reduces lr every 30 eopchs
epochs = 60
for epoch in range(epochs):
    scheduler.step()


/usr/local/lib/python3.12/dist-packages/torch/optim/lr_scheduler.py:192: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn(


FeedForward neural networks

In [ ]:
#general way of writing {y = x.w(T) + b}
# 1. Data (Inputs and Targets)
# "requires_grad=False" because we don't update data, we update weights.
x = torch.tensor([[1.0, 2.0]], requires_grad=False)  # Shape (1, 2)
y_target = torch.tensor([[10.0]], requires_grad=False)

# 2. Weights and Bias (The Learnable Parameters)
# "requires_grad=True" tells PyTorch to track operations on these tensors for backprop.
w = torch.tensor([[0.5, -0.5]], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

# 3. Forward Pass (The Architecture)
# Math: y = x @ w.T + b
y_pred = x @ w.T + b
print(f"Prediction: {y_pred.item():.4f}")

# 4. Loss Calculation
# MSE: (y_pred - y_target)^2
loss = (y_pred - y_target) ** 2
print(f"Loss: {loss.item():.4f}")

# 5. Backward Pass (The Magic)
# This calculates dLoss/dw and dLoss/db and stores them in w.grad and b.grad
loss.backward()

print(f"Gradient dL/dw: {w.grad}")
print(f"Gradient dL/db: {b.grad}")

# 6. Optimization (The Update)
# w_new = w_old - learning_rate * gradient
# We wrap in "no_grad()" because this update step shouldn't be part of the gradient graph.
with torch.no_grad():
    w -= 0.01 * w.grad
    b -= 0.01 * b.grad

    # Crucial: Reset gradients to zero for the next loop, otherwise they accumulate.
    w.grad.zero_()
    b.grad.zero_()


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#Use the standard nn.Module and Optimizer patterns used in industry.
import torch.nn as nn
import torch.optim as optim
# 1. Define the Architecture Class
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        # nn.Linear automatically creates weights (w) and bias (b) for you
        # and initializes them randomly.
        self.layer1 = nn.Linear(in_features=2, out_features=4)
        self.layer2 = nn.Linear(in_features=4, out_features=1)
        self.relu = nn.ReLU()
    def forward(self, x):
        # Define the flow of data
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        return x
# 2. Setup
model = SimpleNet()

criterion = nn.MSELoss()  # Pre-built Mean Squared Error


optimizer = optim.SGD(model.parameters(), lr=0.01) # Handles the "w -= lr * grad" logic

# 3. The Training Loop (Memorize this pattern)
inputs = torch.randn(10, 2) # Batch of 10 samples
targets = torch.randn(10, 1)
for epoch in range(5):
    # A. Reset gradients
    optimizer.zero_grad()
    # B. Forward pass
    outputs = model(inputs)
    # C. Compute loss
    loss = criterion(outputs, targets)
    # D. Backward pass (computes gradients)
    loss.backward()
    # E. Update weights
    optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


#research level implementaion

#1.)Custom Layer (The "Swish" Activation)
class CustomSwish(nn.Module):
    def __init__(self, beta=1.0):
        super().__init__()
        # "nn.Parameter" makes 'beta' a learnable weight.
        # If we just used a float, PyTorch would treat it as a constant.
        self.beta = nn.Parameter(torch.tensor([beta]))
    def forward(self, x):
        # Swish: x * sigmoid(beta * x)
        return x * torch.sigmoid(self.beta * x)

#2.)The Advanced Model Container
class DeepResNet(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()

        self.feature_extractor = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            CustomSwish(), # Using our custom layer
            nn.Linear(hidden_dim, hidden_dim),
            CustomSwish()
        )
        self.head = nn.Linear(hidden_dim, 1)

        # RESEARCHER TRICK: Custom Initialization
        # Loop through all modules and apply specific init logic
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            # Use Xavier initialization for better convergence
            nn.init.xavier_uniform_(module.weight)
            if module.bias is not None:
                nn.init.zeros_(module.bias)

    def forward(self, x):
        # RESEARCHER TRICK: Residual Connection
        # x_new = F(x) + x
        features = self.feature_extractor(x)

        # Skip connection (simple addition) requires dimensions to match
        # Let's assume input_dim == hidden_dim for this example
        if x.shape == features.shape:
            features = features + x

        return self.head(features)


#Debugging & Inspection (The "Why isn't it working?" Phase)
model = DeepResNet(input_dim=10, hidden_dim=10)
inputs = torch.randn(5, 10)
output = model(inputs)
loss = output.mean()
loss.backward()

# TRICK: Inspecting Gradients
# If these are 0 or NaN, your network is dying/exploding.
for name, param in model.named_parameters():
    if param.grad is not None:
        grad_norm = param.grad.norm().item()
        print(f"Layer: {name} | Gradient Norm: {grad_norm:.6f}")

        # Gradient Clipping (prevents explosion)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

Prediction: -0.4000
Loss: 108.1600
Gradient dL/dw: tensor([[-20.8000, -41.6000]])
Gradient dL/db: tensor([-20.8000])
Epoch 1, Loss: 0.4355
Epoch 2, Loss: 0.4330
Epoch 3, Loss: 0.4306
Epoch 4, Loss: 0.4282
Epoch 5, Loss: 0.4262
Layer: feature_extractor.0.weight | Gradient Norm: 1.079492
Layer: feature_extractor.0.bias | Gradient Norm: 0.154606
Layer: feature_extractor.1.beta | Gradient Norm: 0.019144
Layer: feature_extractor.2.weight | Gradient Norm: 0.351044
Layer: feature_extractor.2.bias | Gradient Norm: 0.249840
Layer: feature_extractor.3.beta | Gradient Norm: 0.079616
Layer: head.weight | Gradient Norm: 0.710200
Layer: head.bias | Gradient Norm: 0.359185


In [ ]:
'''
PyTorch "Underscore Rule": Any function ending in an underscore (like ones_ or uniform_)
modifies the tensor in-place. It doesn't return a new tensor; it overwrites the
existing numbers in memory.
'''

'\nPyTorch "Underscore Rule": Any function ending in an underscore (like ones_ or uniform_)\nmodifies the tensor in-place. It doesn\'t return a new tensor; it overwrites the\nexisting numbers in memory.\n'

In [ ]:
#torch.nn.init
'''
torch.nn.init is used to control how a neural network starts learning by
 deciding how weights and biases are initialized before training begins.
'''
import torch.nn as nn
import torch.nn.init as init
# Create a "blank" tensor. It contains whatever random garbage was in your RAM.
w = torch.empty(3, 5)

# Fill every single cell in that 3x5 matrix with the number 1.0.
init.ones_(w)

# Overwrite it: Fill everything with 0.0.
init.zeros_(w)

# Fill everything with exactly 0.42.
init.constant_(w, 0.42)

# Pick numbers randomly between 0 and 1 (Uniform distribution).
init.uniform_(w, a=0, b=1)

# Pick numbers from a Bell Curve (Mean 0, Standard Deviation 0.01).
# This is common for "stable" starts.
init.normal_(w, mean=0, std=0.01)

# Apply to a real layer: Access the '.weight' attribute of the layer.
layer = nn.Linear(1, 5)
init.xavier_uniform_(layer.weight)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# This function is a 'template' that will be run on every layer of your model.
def init_weights(self, m):
    # Check: "Is the current layer a Linear (Fully Connected) layer?"
    if isinstance(m, nn.Linear):
        # Apply 'He Initialization' (Kaiming) designed for ReLU activations.
        init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
        # If the layer has a bias (the '+ b' in y=wx+b), set it to 0.
        # It is standard practice to start biases at zero.
        if m.bias is not None:
            init.zeros_(m.bias)
# .apply() tells PyTorch: "Go through every layer in 'model' and run 'init_weights' on it."

#model.apply(model.init_weights)

In [ ]:
#cnn
import torch.nn as nn

# B = Batch Size, C = Channels, H = Height, W = Width
input_tensor = torch.randn(1, 3, 64, 64)  # A single RGB image of size 64x64

# The Layer
# in_channels=3 (RGB input)
# out_channels=16 (We want to find 16 different types of features)
# kernel_size=3 (The flashlight is a 3x3 grid)
conv_layer = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3)

# The Forward Pass
output = conv_layer(input_tensor)

print(f"Input Shape:  {input_tensor.shape}")
print(f"Output Shape: {output.shape}")
# Output will be [1, 16, 62, 62]. Why 62? We lost pixels at the borders.\


# we wil add padding
# padding=1 preserves spatial dimensions for a 3x3 kernel
conv_preserve = nn.Conv2d(3, 16, kernel_size=3, padding=1)
out = conv_preserve(input_tensor)
# Output Shape: [1, 16, 64, 64] -> Exact match to input height/width


#we will perform stride
# stride=2 cuts dimensions in half
conv_downsample = nn.Conv2d(3, 16, kernel_size=3, padding=1, stride=2)
out = conv_downsample(input_tensor)
# Output Shape: [1, 16, 32, 32]


#perform dilation
# dilation=2 expands the reach
conv_dilated = nn.Conv2d(3, 16, kernel_size=3, dilation=2)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#dont feel if you did'nt understand
#reaearcher level approch
class BottleneckBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()

        mid_channels = out_channels // 4 # Compress by 4x

        # 1. Pointwise Conv: Squeeze channels
        # (Reduces computation for the next step)
        self.conv1 = nn.Conv2d(in_channels, mid_channels, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(mid_channels)

        # 2. Spatial Conv: The actual feature extraction
        # Note the padding=1 to preserve size
        self.conv2 = nn.Conv2d(mid_channels, mid_channels, kernel_size=3,
                               padding=1, stride=stride, bias=False)
        self.bn2 = nn.BatchNorm2d(mid_channels)

        # 3. Pointwise Conv: Expand channels back
        self.conv3 = nn.Conv2d(mid_channels, out_channels, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(out_channels)

        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        residual = x # Store for skip connection

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        # In a real ResNet, you handle shape mismatch here if stride > 1
        if out.shape == residual.shape:
             out += residual

        out = self.relu(out)
        return out

# Verification
block = BottleneckBlock(in_channels=256, out_channels=256)
x = torch.randn(2, 256, 32, 32)
print(block(x).shape) # torch.Size([2, 256, 32, 32])

Input Shape:  torch.Size([1, 3, 64, 64])
Output Shape: torch.Size([1, 16, 62, 62])
torch.Size([2, 256, 32, 32])


In [ ]:
#generative cnn architecture


#upsampling

#Method - 1
# Input: 2x2 Image
x = torch.arange(1, 5).float().view(1, 1, 2, 2)
# Double the size
up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)
out = up(x)
# Output is now 4x4. The network didn't "learn" anything here, just math.

#Method - 2
#To double the size of an image (common in U-Net decoders), the standard setting is kernel_size=2 and stride=2.
# The "Un-Pooling" Layer
# in_channels=16 (high level features)
# out_channels=8 (reducing depth as we grow spatial size)
t_conv = nn.ConvTranspose2d(
    in_channels=16,
    out_channels=8,
    kernel_size=2,
    stride=2
)
input_tensor = torch.randn(1, 16, 32, 32)
output = t_conv(input_tensor)
print(f"Input: {input_tensor.shape}")   # [1, 16, 32, 32]
print(f"Output: {output.shape}")        # [1, 8, 64, 64] -> DOUBLED

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#advanced level

'''
The Problem: ConvTranspose2d often creates ugly "checkerboard" patterns in generated images.
Why? If the kernel size is not divisible by the stride, the "stamps" overlap unevenly. Some pixels get painted twice, some once. This creates a grid artifact.
The Solution (The "Resize-Conv" Pattern): Instead of using ConvTranspose2d, modern researchers (like in Stable Diffusion or modern U-Nets) often prefer a two-step process:
  .)Upsample (using nn.Upsample with 'nearest' or 'bilinear') to grow the size.
  .)Conv2d (standard convolution) to refine the "blurry" upsampled features.
This eliminates artifacts because the upsampling is smooth, and the convolution fixes the details.
'''

class UpSampleBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        # Step 1: Force growth (no parameters)
        self.upsample = nn.Upsample(scale_factor=2, mode='nearest')

        # Step 2: Learn features (parameters)
        # We use padding=1 to keep the new size constant
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)

    def forward(self, x):
        x = self.upsample(x) # 32x32 -> 64x64
        x = self.conv(x)     # Refine features
        return x

Input: torch.Size([1, 16, 32, 32])
Output: torch.Size([1, 8, 64, 64])


In [ ]:
# flattening(a old and un-preffed way)
# Simulation of a CNN output (Batch=1, Channels=2048, H=7, W=7)
features = torch.randn(1, 2048, 7, 7)

# The Flatten Approach
flatten = nn.Flatten()
flat_out = flatten(features)

print(f"Flatten Output: {flat_out.shape}")
# Output: [1, 100352]


#GAP(global average pooling)
# The GAP Approach
# PyTorch idiomatic way: AdaptiveAvgPool2d
# "Adaptive" means: "I don't care what the input size is, give me a 1x1 output."
gap_layer = nn.AdaptiveAvgPool2d((1, 1))
gap_out = gap_layer(features)

print(f"GAP Output (Raw): {gap_out.shape}")  # [1, 2048, 1, 1]

# Remove the extra 1x1 dimensions
final_vector = torch.flatten(gap_out, 1)
print(f"GAP Output (Vector): {final_vector.shape}") # [1, 2048]

Flatten Output: torch.Size([1, 100352])
GAP Output (Raw): torch.Size([1, 2048, 1, 1])
GAP Output (Vector): torch.Size([1, 2048])


Normalization

In [ ]:
'''
Normalization forces the input of every layer to have a consistent
mean (usually 0) and variance (usually 1). This smooths the
optimization landscape.

'''

#BatchNorm-best for CNN

# Input: Batch of 32 images, 3 color channels, 64x64 pixels
input_data = torch.randn(32, 3, 64, 64)
# BatchNorm2d is used for 4D inputs (N, C, H, W)
# We only specify the number of channels (3)
bn = nn.BatchNorm2d(num_features=3)
output = bn(input_data)
print(output.shape) # Still (32, 3, 64, 64)
# The mean of the output across the batch (dim 0) will be approx 0
print(output[:, 0, :, :].mean())


#layer normalization - Best for NLP

# Input: Batch of 2 sentences, 10 words each, embedding size 512
# Shape: (N, Sequence_Length, Embedding_Dim)
nlp_input = torch.randn(2, 10, 512)
# We normalize over the last dimension (512)
ln = nn.LayerNorm(normalized_shape=512)
output = ln(nlp_input)
# The mean is 0 across the embedding dimension (dim 2), not the batch
print(output[0, 0, :].mean())


#GroupNorm - best for object detection

input_data = torch.randn(4, 32, 128, 128) # 32 channels
# Split 32 channels into 8 groups (4 channels per group)
gn = nn.GroupNorm(num_groups=8, num_channels=32)
output = gn(input_data)


#RMSnorm - best for modern LLM

embedding_dim = 512
rms = nn.RMSNorm(embedding_dim)
x = torch.randn(2, 10, 512)
output = rms(x)

torch.Size([32, 3, 64, 64])
tensor(-2.9104e-11, grad_fn=<MeanBackward0>)
tensor(-3.7253e-09, grad_fn=<MeanBackward0>)


In [ ]:
#torch.nn.LayerNorm

'''What is Layer Normalization? Layer Normalization (LayerNorm) normalizes the
input within a specific layer for each sample independently. It makes the data
have a mean of 0 and a standard deviation of 1

It is the standard normalization used in Transformers (BERT, GPT) and RNNs.

Basic Syntax - torch.nn.LayerNorm(normalized_shape, eps=1e-05, elementwise_affine=True)

'''

#hello world

input_tensor = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0]])
# 2. Define LayerNorm
# normalized_shape=5 means we want to normalize across the last 5 dimensions
layer_norm = nn.LayerNorm(normalized_shape=5)
# 3. Apply it
output = layer_norm(input_tensor)


#handling dimensions - NLP
batch_size = 2
seq_len = 3
embed_dim = 4
input_data = torch.randn(batch_size, seq_len, embed_dim)
# We want to normalize over the last dimension (size 4)
# This calculates 1 mean and 1 std per word.
ln = nn.LayerNorm(normalized_shape=embed_dim)
output = ln(input_data)
print(f"Input shape: {input_data.shape}")
print(f"Output shape: {output.shape}") # Shape remains the same


#handling dimension - global (sometimes you may want to perform this layernorm on entire image)
N, C, H, W = 1, 3, 32, 32
img_data = torch.randn(N, C, H, W)
# Normalize over Channels, Height, and Width together
ln_image = nn.LayerNorm(normalized_shape=[C, H, W])
out_img = ln_image(img_data)
# Now, the Mean is calculated over all 3x32x32 pixels at once.

Input shape: torch.Size([2, 3, 4])
Output shape: torch.Size([2, 3, 4])


Embeeding's

In [ ]:
'''
basic syntax:
  torch.nn.Embedding(num_embeddings, embedding_dim)

  .)num_embeddings: Size of the dictionary (e.g., Vocabulary size: 1000 words).
  .)embedding_dim: Size of the vector you want for each word (e.g., 64, 128, 512).

It is crucial to understand that nn.Embedding does not perform
matrix multiplication (like a Linear layer). It performs array indexing.
'''

#hello world code

# 1. Setup the layer
# vocab_size = 5 (Indices 0, 1, 2, 3, 4)
# dim = 3 (Each ID becomes a list of 3 numbers)
embedding = nn.Embedding(num_embeddings=5, embedding_dim=3)
# 2. Define input indices (Must be Integers/Longs)
# Let's say we want the vectors for word_id 1 and word_id 4
input_indices = torch.tensor([1, 4])
# 3. Pass through layer
output = embedding(input_indices)
print("Input:", input_indices)
print("Output:\n", output)
print("Output Shape:", output.shape)
# Shape will be [2, 3] -> [Number of Inputs, Embedding Dim]


#weights in embeeding

# Access the raw weight matrix
# Shape: [5, 3]
print("All Weights:\n", embedding.weight)
# Let's verify that the embedding layer is just doing a lookup
# We manually pick row 1 from the weights
manual_selection = embedding.weight[1]
# We use the layer to get index 1
layer_selection = embedding(torch.tensor(1))
print("\nAre they the same?")
print(torch.equal(manual_selection, layer_selection)) # True


#handling padding

#The padding_idx argument tells PyTorch: "Keep the vector at this index as Zeros and do not update it."
# vocab_size=10, dim=4, padding_index is 0
embedding_padded = nn.Embedding(10, 4, padding_idx=0)
# Input batch: Two sentences
# Sentence 1: [1, 2, 3] (Length 3)
# Sentence 2: [4, 0, 0] (Length 1, padded with two 0s)
input_batch = torch.tensor([
    [1, 2, 3],
    [4, 0, 0]
])
out = embedding_padded(input_batch)
print("Vector for index 4 (Normal word):\n", out[1][0])
print("Vector for index 0 (Pad token):\n", out[1][1])
# You will see the pad vector is all Zeros.

Input: tensor([1, 4])
Output:
 tensor([[-0.1378,  0.7484, -0.0948],
        [-0.9935,  0.3337, -1.4064]], grad_fn=<EmbeddingBackward0>)
Output Shape: torch.Size([2, 3])
All Weights:
 Parameter containing:
tensor([[-0.0975,  0.5610,  1.1065],
        [-0.1378,  0.7484, -0.0948],
        [-2.0776, -0.6813,  0.0305],
        [-0.8480,  0.2581,  0.3481],
        [-0.9935,  0.3337, -1.4064]], requires_grad=True)

Are they the same?
True
Vector for index 4 (Normal word):
 tensor([-0.4762,  0.5257,  0.1441, -0.5528], grad_fn=<SelectBackward0>)
Vector for index 0 (Pad token):
 tensor([0., 0., 0., 0.], grad_fn=<SelectBackward0>)


Transformers

In [ ]:
'''
Before the model thinks, it needs to represent the data.
A Transformer expects an input of shape (Batch_Size, Seq_Len, Dim).
'''

#posistional encoding

import math
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        # Create a matrix of [max_len, d_model] representing positional encodings
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        # Apply sine to even indices, cosine to odd indices
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        # Add a batch dimension: [1, max_len, d_model]
        pe = pe.unsqueeze(0)

        # register_buffer tells PyTorch this is a state, but not a learnable parameter
        self.register_buffer('pe', pe)

    def forward(self, x):
        # x shape: [batch_size, seq_len, d_model]
        # We add positional encoding up to the current sequence length
        x = x + self.pe[:, :x.size(1)]
        return x